### ISSUE TITLE
No valid hostname while creating entry for NS "_acme-challenge.doma.in"

### ISSUE THREAD

**Issue by dirkzado** [krtab/agnos#10]
Thank you for this project. I'm trying to create all necessary steps (which are mentioned in the readme).

But I have an issue while setting the NS entry "_acme-challenge.mydomain.de":

![image](https://user-images.githubusercontent.com/13819477/187026319-9b5381bb-9cad-4a1b-9260-bccb6cdfe528.png)

It always says that is not a valid hostname. It seems that the underline as a first character does not work or rather is not valid in my configuration (at DomainFactory).

Do you habe any suggestions?

**Comment by krtab** [comment]
Hi!

Thanks a lot for your interest in this project!

Unfortunately, the "_acme-challenge" prefix comes from the DNS-01 specification, so if your domain registar does not allow you to add such a domain, there is nothing agnos can do.

The let's encrypt forum may be able to help you, or you can try contacting your registar support. Best of luck!
