### ISSUE TITLE
Compile for Debian BullsEye

### ISSUE THREAD

**Issue by fayeg21** [krtab/agnos#31]
FYI two things make using this tool dificult for Debian Bullseye:
1. The binary release has a ldd issue with libsss.so.3
2. The source code is too new for using with Debian 11's cargo/rust install (from apt).

This means that adopting agnos has a high barrier to overcome on Debian 11.

Could something be done about this please?

**Comment by krtab** [comment]
That's a common problem with Debian, and not one I have an easy solution for. Debian's choice to ship old versions of software does not play well with Rust's update pace. Debian 11 is shipping Rust 1.48 while this crates dependencies require rust 1.64 at least. I can try to have an old Debian building on CI but that isn't too high on my priority at the moment. I have however updated the Readme to encourage using `rustup`.

**Comment by krtab** [comment]
I've added static binaries to the last release, which should work fine for you, can you let me know it that solved your issue?
