### ISSUE TITLE
Typo in configuration

### ISSUE THREAD

**Issue by krtab** [krtab/agnos#34]
There is a typo in the configuration: `dns_listen_adr` would better be  `dns_listen_addr`. Unfortunately, fixing this requires a breaking release.

**Comment by justinas** [comment]
Agnos could support both for the time being (and maybe emit a warning when using the incorrect one). But I'd say that the best time to break things is before 0.1 final is released :slightly_smiling_face:

**Comment by krtab** [comment]
Closed in 7962f1a
